Try to disable GCloud prompts on Travis.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -43,16 +43,22 @@ jobs:
       language: java
       jdk:
           - oraclejdk8
-      env:
-        global:
-          # Do not prompt for user input when using any SDK methods.
-          - CLOUDSDK_CORE_DISABLE_PROMPTS=1
+      cache:
+        directories:
+        - "$HOME/google-cloud-sdk/"
+      #env:
+      # global:
+      # Do not prompt for user input when using any SDK methods.
+      #- CLOUDSDK_CORE_DISABLE_PROMPTS=1
       before_install:
         - chmod +x gradlew
-        - if [ ! -d $HOME/google-cloud-sdk ]; then
-          curl https://sdk.cloud.google.com | bash;
-          fi
-        - gcloud version
+        - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
+        # Add gcloud to $PATH
+        - source $HOME/travis/google-cloud-sdk/path.bash.inc
+        #- if [ ! -d $HOME/google-cloud-sdk ]; then
+        #  curl https://sdk.cloud.google.com | bash;
+        #  fi
+        - gcloud version || echo "GCloud installation failed."
         # Here we use the decrypted service account credentials to authenticate the command line tool.
         - gcloud auth activate-service-account --key-file deployment/appengine-web/src/main/resources/spine-dev.json
       install:
